const interpolaterToEnglish = {
    "abais": "but",
    "aktion": "action",
    "albiner": "white",
    "apolies": "sorry",
    "ba": "?",
    "baksu": "box",
    "bévakoof": "stupid",
    "béyâhend": "okay",
    "blemiken": "speak",
    "bligau": "blue",
    "boissonus": "drink",
    "boissonen": "drink (verb)",
    "bom": "good",
    "bomer": "love",
    "bonat": "gift",
    "buhdich": "dumb",
    "centrum": "I/me",
    "cerebrent": "know",
    "cerebrum": "brain",
    "cha": "coffee",
    "chay": "something",
    "chistando": "joke",
    "chukas": "cat",
    "dawr": "role",
    "daz": "that",
    "degistermen": "change",
    "direken": "tell",
    "diktonary": "dictionary",
    "diz": "this",
    "donem": "give",
    "dormiren": "sleep",
    "durbius": "animal",
    "dzai": "is in/on",
    "dzwo": "left",
    "e": "and",
    "ego": "I/me",
    "en": "in",
    "equival": "equal",
    "ergo": "so",
    "exlirent": "explain",
    "fache": "do",
    "fazen": "make",
    "feminas": "woman",
    "folaaz": "metal",
    "folaazpersone": "robot",
    "fransosik": "France",
    "genus": "gender",
    "ghurfa": "room",
    "go": "I/me",
    "granda": "very",
    "gratien": "thanks",
    "haiben": "have",
    "halo": "hello",
    "hamborgar": "hamburger",
    "hic": "here",
    "hicsolum": "today",
    "homo": "same",
    "homoparole": "homonym",
    "homosignum": "synonym",
    "imaj": "image",
    "ind": "have",
    "inglisik": "English",
    "intelgenri": "smart",
    "intapole": "secret",
    "ist": "is",
    "italiski": "Italy",
    "jeulo": "yellow",
    "kayen": "can",
    "ke": "what",
    "keken": "laugh",
    "ke tal": "what's up",
    "keyöntemus": "how",
    "keyuzwo": "with",
    "komorenden": "understand",
    "kribân": "soon",
    "kulora": "colour",
    "laterin": "toilet",
    "lii": "inside",
    "lingue": "language",
    "lun": "moon",
    "lunum": "night",
    "marok": "Morocco",
    "marokan": "Moroccan",
    "maskulinas": "man",
    "me": "shows it is directed to me",
    "monomus": "only",
    "mort": "dead",
    "morten": "kill",
    "mui": "very",
    "nain": "no",
    "naint": "not",
    "nainbom": "bad",
    "nainchay": "nothing",
    "nainthomo": "different",
    "nazion": "nation",
    "nôchüch": "annoying",
    "noi": "we/us",
    "nomus": "name",
    "noven": "new",
    "numerus": "number",
    "omni": "every",
    "omniblemiken": "announce",
    "omniblemikus": "announcement",
    "omnipersoni": "everyone",
    "onnoek": "genderless",
    "oranj": "orange",
    "ow": "or",
    "parole": "word",
    "pensen": "think",
    "per": "to",
    "perr": "too",
    "personepumilus": "poll",
    "persone": "people",
    "pien": "because",
    "pizza": "pizza",
    "praesen": "present",
    "prochrono": "future tense marker",
    "pumilen": "choose",
    "pumilus": "choice",
    "quanchrono": "when",
    "quus": "anybody",
    "reglus": "rule",
    "route": "red",
    "se": "shows it is directed to them",
    "sang": "up",
    "sangaktiven": "fun",
    "sangchay": "important",
    "shangaro": "angel",
    "shishten": "poop",
    "shworz": "black",
    "shworza": "black coffee",
    "signum": "meaning",
    "sol": "sun",
    "solsang": "sunrise",
    "solsya": "sunset",
    "solum": "day",
    "sum": "am",
    "susaly": "auto",
    "sya": "down",
    "syaaktiven": "bored",
    "te": "shows it is directed to you",
    "tu": "you",
    "tuf": "apple",
    "urinam": "urinate",
    "usa": "use",
    "vescum": "eat",
    "viden": "see",
    "vïowl": "purple",
    "vocarus": "voice",
    "vor": "for",
    "vorke": "why",
    "volerem": "want",
    "vruncha": "green tea",
    "vrün": "green",
    "wilkvenden": "welcome",
    "woru": "tired",
    "yönetmekus": "administrator",
    "yönetmen": "administrate",
    "yöntemus": "method",
    "you": "right",
    "za": "tea",
    "zi": "yes",
};

const englishToInterpolater = Object.fromEntries(
    Object.entries(interpolaterToEnglish).map(([key, value]) => [value, key])
);

function translateToInterpolater() {
    const input = document.getElementById("inputText").value.toLowerCase();
    const words = input.split(" ");
    const translatedWords = words.map(word => interpolaterToEnglish[word]);
    
    // Check if all words were translated
    if (translatedWords.includes(undefined)) {
        document.getElementById("outputText").value = "Error: One or more words cannot be translated.";
    } else {
        document.getElementById("outputText").value = translatedWords.join(" ");
    }
}

function translateToEnglish() {
    const input = document.getElementById("inputText").value.toLowerCase();
    const words = input.split(" ");
    const translatedWords = words.map(word => englishToInterpolater[word]);
    
    // Check if all words were translated
    if (translatedWords.includes(undefined)) {
        document.getElementById("outputText").value = "Error: One or more words cannot be translated.";
    } else {
        document.getElementById("outputText").value = translatedWords.join(" ");
    }
}
